version: '3'
services:

  zookeeper:
    container_name: jdbc-zookeeper
    image: quay.io/debezium/zookeeper:2.3
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    container_name: jdbc-kafka
    image: quay.io/debezium/kafka:2.3
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  mysql:
    container_name: jdbc-mysql
    image: quay.io/debezium/example-mysql:2.3
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=dbz
      - TZ=Europe/Vienna
    command:
      ./entrypoint.sh --default-time-zone="SYSTEM"

  postgres:
    container_name: jdbc-postgres
    image: quay.io/debezium/example-postgres:2.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dbz
      - TZ=Europe/Vienna
      - PGTZ=Europe/Vienna

  connect:
    container_name: jdbc-connect
    image: quay.io/debezium/connect:2.3
    ports:
      - "8083:8083"
    links:
      - kafka
      - mysql
      - postgres
    depends_on:
      - kafka
      - mysql
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses